SRCS = srcs/ft_atoi.c srcs/ft_putchar.c srcs/ft_putnbr.c srcs/ft_putstr.c srcs/ft_operator.c
OBJS = srcs/ft_atoi.o srcs/ft_putchar.o srcs/ft_putnbr.o srcs/ft_putstr.o srcs/ft_operator.o
TARGET = do-op

